### ISSUE TITLE
cross-compiler version issues

### ISSUE THREAD

**Issue by Stane1983** [scakemyer/cross-compiler#1]
Hi,

I'll open issue here because it's strictly related to cross compiler.
1. With commit 70ac1c8d1da387561bf4cfd5e0eb887c210dad36 you switched to Debian Jessie repositories. That causes issues on Ubuntu 14.04 LTS (with latest updates) because libstdc++ is missing GLIBCXX_3.4.20 (I think that's version, don't have log anymore).
2. With commit 6f3f2cf70725ef02fce916e8715e6e28c817bcbc you created armv7 platform based on gcc 4.9. This is similar issue which may not affect many users but affects mine armv7 project which has to be compiled with gcc 4.7 (kernel and bootloader issues if I use higher versions). When replacing armv7 daemon with arm it works fine. So I suggest to solve this issue by falling back to arm daemon if armv7 fails to load (in addon).

**Comment by scakemyer** [comment]
We can't do fallbacks with the add-on, since it would require the all-binaries package which we can't assume is what the user installs, the built-in repo never uses that package either, and we wouldn't be able to know if what's causing a crash or failure to load would be solved at run-time by a fall back.

I also won't be going back to Wheezy or adding workarounds to use an older libstdc++. Ubuntu should update their shit on Trusty, that's what LTS is supposed to stand for, especially when Debian-stable has it.

As for armv7, just stick with linux-arm, not going to downgrade that one either. Feel free to fork the cross-compiler if you require old versions.
